language: ruby
rvm:
  - 2.1.2
cache: bundler

# bundler_args: --without production

before_script:
  - mysql -e 'create database myapp_test;'
  - mv config/database.yml.example config/database.yml
  - bundle exec rake db:test:prepare
