language: ruby
rvm:
  - 2.1.2
cache: bundler

# bundler_args: --without production

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

before_script:
  - mysql -e 'create database myapp_test;'
  - mv config/database.yml.example config/database.yml
